# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 20:48
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pokój')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numer')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Opis')),
                ('faculty_description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Wydział')),
            ],
            options={
                'verbose_name': 'Tablica',
                'verbose_name_plural': 'Tablice',
            },
        ),
    ]
